name: flutter_component_library
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  logger: ^2.3.0              #日志管理
  flutter_screenutil: ^5.9.0  #屏幕适配
  flutter_svg: 2.0.8          #svg图片显示
  pretty_dio_logger: 1.3.1    #日志格式管理

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

